// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class LogError
{
    public int ErrorId { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime ErrorTime { get; set; }

    public string ErrorSource { get; set; }

    public string ErrorRemark { get; set; }

    public string HttpMethod { get; set; }

    public string RequestUrl { get; set; }

    public int? ResponseStatusCode { get; set; }

    public string CorrelationId { get; set; }
}