// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class LogProduct
{
    public int LogProductId { get; set; }

    public int? ProductId { get; set; }

    public string Action { get; set; }

    public string ProductName { get; set; }

    public decimal Price { get; set; }

    public string Detail { get; set; }

    public int Quantity { get; set; }

    public string ImagePath { get; set; }

    public string StatusProductCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }
}