// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class Navbar
{
    public int NavbarId { get; set; }

    public string NavbarName { get; set; }

    public string PageCode { get; set; }

    public int Seq { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual RefPage PageCodeNavigation { get; set; }
}