// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class ProductCategory
{
    public int ProductCategoryId { get; set; }

    public int CategoryId { get; set; }

    public int ProductId { get; set; }

    public virtual Category Category { get; set; }

    public virtual Product Product { get; set; }
}