// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class RefPage
{
    public string PageCode { get; set; }

    public string PageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual ICollection<MapRolePage> MapRolePages { get; set; } = new List<MapRolePage>();

    public virtual ICollection<Navbar> Navbars { get; set; } = new List<Navbar>();
}