// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class Role
{
    public string RoleCode { get; set; }

    public string RoleName { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual ICollection<LogUser> LogUsers { get; set; } = new List<LogUser>();

    public virtual ICollection<MapRolePage> MapRolePages { get; set; } = new List<MapRolePage>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}