// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class RunningNumber
{
    public int Year { get; set; }

    public int LastNumber { get; set; }
}