// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HomeWork.Domain.Models;

public partial class UserRole
{
    public int UserRoleId { get; set; }

    public int UserId { get; set; }

    public string RoleCode { get; set; }

    public virtual Role RoleCodeNavigation { get; set; }

    public virtual User User { get; set; }
}